travis:
  secure:
    BINSTAR_TOKEN: MFvNH/o658fQjBdeZivvj1+o6KzlGYTKJCUaoRTWE6GLR61IN0YUNCU2wyu6o+N3tFQT3NT+7wNHexFvSvWRzNanZhW6AwjRAtxv5csJONy0SSGyXzuYs/j1k30f4t5Znae8A6iL68eAWJviaglX32zMNjS5OmDJ01rnjYirmH67/HaHLtMll+zeVDrdXqSzmT+VbaOwxVD16q8wRqF976jOXtmSlrmQmfKvYyBYofGCLotqOQXZphlMYEp3Bc/WnGAh1cWcRmy0M5qe8bIKXD9UkO/rxBjuP/6cb1HM/uIPgK8D8xwAyjkx5NlcQGxp9UeOg4nQ8jOYJWQ1nYcmRY/n8nVp0g510qZ8/fowViI5Wv0IdCVVqMNPaVkKCYB4DXVUx9n7PxDRXMjyi0XgriNPJV19pw7L+/VAXX2RPi0UxxFV2YmhB8HoLruLVcss0MnAYmyW+6mmgrd9u/MkGZOXTyOI2nqqy/RVGyNStLMUgJ/bNvj0SUMOIsaKgQFW6H5NnyzxghoEdK1E3UAoMe1QRdk3DHvz9aaoU5/zN9XAx7gZgk4nW/iEwRxynig7x957O4nDnkcLMqqg7gClLXE6wXvNPnX1hKrjLUGcL6pPOlFG/USaaaFHa5UANlfkZReEAG4o20amQnkFAw+ltl5kA8WGHDTjkFp3FbLdors=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
